version: '3.4'

services:
  web:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    volumes:
      - ./webapp:/app
    working_dir: /app
    command: dotnet watch run --urls http://+:80
    ports:
      - 8845:80
